# compose config created for development purposes
version: '2'
services:
  api:
    image: node:carbon
    command: npm start
    volumes:
     - ./:/app
    working_dir: /app
    ports:
     - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
   image: mysql:5.6
   environment:
     MYSQL_ROOT_PASSWORD: root
   ports:
     - 3306:3306
   volumes:
     - ./db-dump:/docker-entrypoint-initdb.d